        {
            .desc = "Convert positive decimal to binary",
            .nbr = "42",
            .base_from = "0123456789",
            .base_to = "01",
            .expected = "101010",
        },
        {
            .desc = "Convert negative decimal to binary",
            .nbr = "-42",
            .base_from = "0123456789",
            .base_to = "01",
            .expected = "-101010",
        },
        {
            .desc = "Convert binary to hexadecimal",
            .nbr = "101010",
            .base_from = "01",
            .base_to = "0123456789ABCDEF",
            .expected = "2A",
        },
        {
            .desc = "Invalid base_from",
            .nbr = "42",
            .base_from = "0012345678",
            .base_to = "01",
            .expected = NULL,
        },
        {
            .desc = "Invalid base_to",
            .nbr = "42",
            .base_from = "0123456789",
            .base_to = "01a ",
            .expected = NULL,